---
# Make sure zsh is installed and set to the user's default shell.
- name: "OMZ | include tasks from zsh.yml."
  ansible.builtin.include_tasks:
    file: "zsh.yml"
    apply:
      tags:
        - "zsh"
        - "configure"
        - "configurezsh"

# Install oh-my-zsh.
- name: "OMZ | include tasks from oh-my-zsh-install.yml."
  ansible.builtin.include_tasks:
    file: "oh-my-zsh-install.yml"
    apply:
      tags:
        - "oh-my-zsh"
        - "install"
        - "installohmyzsh"

## Configure oh-my-zsh with a custom .zshrc template if omz_zshrc_create
## is set to 'true'.
#- name: "OMZ | include tasks from oh-my-zsh-zshrc.yml."
#  ansible.builtin.include_tasks:
#    file: "oh-my-zsh-zshrc.yml"
#    apply:
#      tags:
#        - "oh-my-zsh"
#        - "configure"
#        - "configureohmyzsh"
#
## Finally, add exports etc to .zshrc /last/ (i.e. so they get added to whaterver
## .zshrc exists.
#- name: "OMZ | include tasks from zsh-zshrc.yml."
#  ansible.builtin.include_tasks:
#    file: "zsh-zshrc.yml"
#    apply:
#      tags:
#        - "zsh"
#        - "configure"
#        - "configurezsh"
