---
# Make sure zsh is installed and set to the user's default shell.
- name: "OMZ | include tasks from zsh.yml."
  ansible.builtin.include_tasks:
    file: "zsh.yml"
    apply:
      tags:
        - "zsh"
        - "configure"
        - "configurezsh"

# Install oh-my-zsh.
- name: "OMZ | include tasks from oh-my-zsh-install.yml."
  ansible.builtin.include_tasks:
    file: "oh-my-zsh-install.yml"
    apply:
      tags:
        - "oh-my-zsh"
        - "install"
        - "installohmyzsh"

# Template a custom .zshrc file if omz_zshrc_create == true.
- name: "OMZ | include tasks from oh-my-zsh-zshrc.yml."
  ansible.builtin.include_tasks:
    file: "oh-my-zsh-zshrc.yml"
    apply:
      tags:
        - "oh-my-zsh"
        - "configure"
        - "configureohmyzsh"

# Add exports etc to the end of .zshrc (so they override existing settings).
- name: "OMZ | include tasks from zsh-zshrc.yml."
  ansible.builtin.include_tasks:
    file: "zsh-zshrc.yml"
    apply:
      tags:
        - "zsh"
        - "configure"
        - "configurezsh"
