---
- name: "OMZ | clone Oh My ZSH repo for user."
  ansible.builtin.git:
    repo: "{{ omz_git_repository }}"
    dest: "{{ omz_install_path }}"
    update: true
    accept_hostkey: true
    version: "master"
  become: true
  become_user: "{{ omz_user.name }}"
