---
- name: "OMZ | ensure zsh is installed."
  block:
    - name: "OMZ | install zsh for Linux using 'package' module."
      ansible.builtin.package:
        name: "zsh"
        state: "present"
      when:
        - "ansible_system == 'Linux'"
        - "omz_install_zsh"

    - name: "OMZ | install zsh for macOS using 'homebrew' module."
      community.general.homebrew:
        name: "zsh"
        state: "present"
      when:
        - "ansible_system == 'Darwin'"
        - "omz_install_zsh"

- name: "OMZ | get zsh installed path."
  ansible.builtin.shell: "command -v zsh"
  register: omz_zsh_installed_path
  changed_when: false
  failed_when: "omz_zsh_installed_path.stdout == 1"

- name: "OMZ | set user shell to zsh."
  ansible.builtin.user:
    name: "{{ omz_user.name }}"
    shell: "{{ omz_zsh_installed_path.stdout }}"
